#!/bin/bash

slist=$1

prot_down()
{
pro_name=( $(grep -i "$sid" $slist ) )
count=${#pro_name[@]}
echo $count

for (( i=0 ; i<count ; i++ ))
do
        mkdir ${pro_name[i]}
        cd ${pro_name[i]}
        wget $ref/${pro_name[i]}/*.faa*
        cd ..
done
}

ref="ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Bacteria"

for (( i=0 ; i<99 ; i++ ))
do      
        while [ $i -le 99 ]
        do 
                read -p "Do you want to continue (y/n)" answer
                        if [ $answer = y ] ; then
                                read -p "Enter query id: " sid
                                prot_down()
                        else
                                echo "You need to enter query id. Goodbye."
                                exit 1
                        fi
        done
done

