#!/bin/bash
#	Name of Script:		tree_o_matic.sh
#	Purpose of Script:	Creating phylogenetic trees from protein or DNA sequences
#	Author's Name:		Maria G. Hinojosa, Graduate Student
#	Affiliation:		TAMIU
#	Date created:		Sun Apr 30 16:23:54 CDT 2017
#	Date modified:			

# Usage notes: 

read -p "Please input unzipped fasta file name (protein or nucleotide): " Fname
#echo $Fname
read -p "Does $Fname file contain a protein or nucleotide sequence?: " seq_type
#echo $seq_type
read -p "Enter output file name for blast: " f_out



prot_blast () 
{
	blastp -query "$Fname" -db swissprot -out "$f_out" -max_target_seqs 50 -outfmt 6 -remote
}






if [ -f $Fname ] && [ -s $Fname ] && [ ! -z $Fname ] ; then
	echo "File exists and is not empty"
	prot_blast
else
	echo "Either no file was inputted or file was empty. Try again."
	exit 1
fi 

MNYDLIIIGAGPAGYVAAEYAGKHKLKTLVVEKEYFGGVCLNVGCIPTKTLLKRAKIVDY
LRHAQDYGISINGQVALNWNQLLEQKGKVVSKLVGGVKAIIASAKAETVMGEAKVLDPNT
VEVAGKTYTTKSIVVATGSRPRYLTLPGFAEARQNGFVIDSTQALSLEGVPRKLVVVGGG
VIGIEFAFLYASLGSEVTILQGVDRILEIFDTEVSDLVAKLLQTKNVKIITNAQVTRANN
NEVFYSQNGQEGSVVGDRILVSIGRIPNTECLDGLNLQRDERNRIVLNQDLQTSIPNIYI
VGDANAQLMLAHFAYQQGRYAVNHILNKKQVKPAQKLTCPSCIYTNPEVASVGYTEMELK
KQGIPYVKTNLVLAHCGKAIADNETNGFVKMMFDPQTGKILGCCIIAATASDMIAELALA
MGAGLTVFDIANSISPHPTINEMIADVCKKALFDHFK


atttttctgagagtttgatcctggctcaggattaacgctggcggcatgcctaatacatgc
aagtcgatcgaaagtagtaatactttagaggcgaacgggtgagtaacacgtatccaatct
accttataatgggggataactagttgaaagactagctaataccgcataagaactttggtt
cgcatgaatcaaagttgaaaggacctgcaagggttcgttatttgatgagggtgcgccata
tcagctagttggtggggtaacggcctaccaaggcaatgacgtgtagctatgctgagaagt
agaatagccacaatgggactgagacacggcccatactcctacgggaggcagcagtaggga
atttttcacaatgagcgaaagcttgatggagcaatgccgcgtgaacgatgaaggtcttta
agattgtaaagttcttttatttgggaagaatgactttagcaggtaatggctagagtttga
ctgtaccattttgaataagtgacgactaactatgtgccagcagtcgcggtaatacatagg
tcgcaagcgttatccggatttattgggcgtaaagcaagcgcaggcggattgaaaagtctg
gtgttaaaggcagctgcttaacagttgtatgcattggaaactattaatctagagtgtggt
agggagttttggaatttcatgtggagcggtgaaatgcgtagatatatgaaggaacaccag
tggcgaaggcgaaaacttaggccattactgacgcttaggcttgaaagtgtggggagcaaa
taggattagataccctagtagtccacaccgtaaacgatagatactagctgtcggggcgat
cccctcggtagtgaagttaacacattaagtatctcgcctgggtagtacattcgcaagaat
gaaactcaaacggaattgacggggacccgcacaagtggtggagcatgttgcttaattcga
cggtacacgaaaaaccttacctagacttgacatccttggcaaagttatggaaacataatg
gaggttaaccgagtgacaggtggtgcatggttgtcgtcagctcgtgtcgtgagatgttgg
gttaagtcccgcaacgagcgcaacccttatcgttagttacattgtctagcgagactgcta
atgcaaattggaggaaggaagggatgacgtcaaatcatcatgccccttatgtctagggct
gcaaacgtgctacaatggccaatacaaacagtcgccagcttgtaaaagtgagcaaatctg
taaagttggtctcagttcggattgagggctgcaattcgtcctcatgaagtcggaatcact
agtaatcgcgaatcagctatgtcgcggtgaatacgttctcgggtcttgtacacaccgccc
gtcaaactatgaaagctggtaatatttaaaaacgtgttgctaaccattaggaagcgcatg
tcaaggatagcaccggtgattggagttaagtcgtaacaaggtacccctacgagaacgtgg
gggtggatcacct


